name: ansible-lint
on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        id: lint
        uses: ansible/ansible-lint@main
        with:
          args: --force-color
          setup_python: "true"
          working_directory: ./ansible
          requirements_file: requirements.yml
        continue-on-error: true

      - name: Set Output
        id: set_output
        run: |
          lint_output=$(ansible-lint ./ansible || true)

          echo "lint output: $lint_output"

          OUTPUT_FILE="lint_output.txt"
          echo "### Ansible Lint Results" | tee -a $GITHUB_STEP_SUMMARY $OUTPUT_FILE
          echo "$lint_output" | tee -a $GITHUB_STEP_SUMMARY $OUTPUT_FILE
          
          echo "lint_output_file=$OUTPUT_FILE" >> "$GITHUB_OUTPUT"
        continue-on-error: true

  job-summary:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Workflow Job Summary
        run: |
          echo "## Ansible Lint Result" >> $GITHUB_STEP_SUMMARY
          cat ${{ needs.lint.outputs.lint_output_file }} >> $GITHUB_STEP_SUMMARY
