name: Ansible CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-ci-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Instantiate Ubuntu VM & Execute Test Playbook
      run: vagrant up